main.py
from flask import Flask
from routes.home import home_route
from routes.cliente import cliente_route

app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix='/clientes')

app.run(debug=True)

routes/cliente.py
from flask import Blueprint, request, redirect, url_for, render_template
from database.cliente import CLIENTES

cliente_route = Blueprint('cliente', __name__)

"""Listar Clientes"""
@cliente_route.route("/")
def lista_clientes():
    return render_template('lista_clientes.html', clientes=CLIENTES)

'''Página Cadastrar'''
@cliente_route.route("/cadastrar")
def pagina_cadastrar():
    return render_template('form.html')

'''Usuario cadatrado'''
@cliente_route.route("/sucesso")
def pagina_sucesso():
    return render_template('sucesso.html')


@cliente_route.route("/", methods=["POST"])
def inserir_cliente():
    data = request.form
    
    # Cria um novo cliente e insere na lista
    novo_cliente = {
        "id": len(CLIENTES) + 1,
        "nome": data.get("nome", ""),  # Nome do cliente
        "idade": data.get("idade", ""),  # Idade do cliente
        "sexo": data.get("sexo", ""),  # Sexo do cliente
        "altura": data.get("altura", ""),  # Altura do cliente
        "peso": data.get("peso", ""),  # Peso do cliente
        "pressao_arterial": data.get("pressao_arterial", ""),  # Pressão arterial do cliente
        "alergias": data.get("alergias", ""),  # Alergias do cliente
        "medicamentos_em_uso": data.get("medicamentos_em_uso", ""),  # Medicamentos em uso
        "fuma": data.get("fuma", ""),  # O cliente fuma?
        "bebe": data.get("bebe", ""),  # O cliente bebe?
        "parentes_com_doencas": data.get("parentes_com_doencas", ""),  # Parentes com doenças
    }

    CLIENTES.append(novo_cliente)

    # Redirecionar para a página de sucesso
    return redirect(url_for("cliente.pagina_sucesso"))

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

templates/form.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulário de Informações Médicas</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<div class="container mt-5">

    <h2>Formulário de Informações Médicas</h2>

    <form id="formMedico"  action="{{ url_for('cliente.inserir_cliente') }}" method="POST">

        <div class="form-group">
            <label for="nome">Nome:</label>
            <input type="text" class="form-control" id="nome" name="nome" placeholder="Digite seu nome">
        </div>

        <div class="form-group">
            <label for="idade">Idade:</label>
            <input type="number" step="0.1"class="form-control" id="idade" name="idade" placeholder="Digite sua idade">
        </div>

        <div class="form-group">
            <label for="sexo">Sexo:</label>
            <select class="form-control" id="sexo" name="sexo">
                <option value="masculino">Masculino</option>
                <option value="feminino">Feminino</option>
                <option value="outro">Outro</option>
            </select>
        </div>

        <div class="form-group">
            <label for="altura">Altura :</label>
            <input type="number" step="0.01" class="form-control" id="altura" name="altura" placeholder="Digite sua altura">

        </div>

        <div class="form-group">
            <label for="peso">Peso (kg):</label>
            <input type="number" class="form-control" id="peso" name="peso" placeholder="Digite seu peso">
        </div>

        <div class="form-group">
            <label for="pressao_arterial">Pressão Arterial:</label>
            <input type="text" class="form-control" id="pressao_arterial" name="pressao_arterial" placeholder="Digite a pressão arterial">
        </div>

        <div class="form-group">
            <label for="alergias">Alergias:</label>
            <textarea class="form-control" id="alergias" name="alergias" rows="2" placeholder="Liste suas alergias"></textarea>
        </div>

        <div class="form-group">
            <label para="medicamentos_em_uso">Medicamentos em uso:</label>
            <textarea class="form-control" id="medicamentos_em_uso" name="medicamentos_em_uso" rows="2" placeholder="Quais medicamentos está usando?"></textarea>
        </div>

        <div class="form-group">
            <label para="fuma">Fuma:</label>
            <select class="form-control" id="fuma" name="fuma">
                <option value="sim">Sim</option>
                <option value="não">Não</option>
            </select>
        </div>

        <div class="form-group">
            <label para="bebe">Bebe:</label>
            <select class="form-control" id="bebe" name="bebe">
                <option value="sim">Sim</option>
                <option value="não">Não</option>
            </select>
        </div>

        <div class="form-group">
            <label para="parentes_com_doencas">Parentes com doenças:</label>
            <textarea class="form-control" id="parentes_com_doencas" name="parentes_com_doencas" rows="2" placeholder="Liste parentes com doenças"></textarea>
        </div>
        
        <button    class="btn btn-primary">Enviar</button>

        <a href="http://localhost:5000/" type="submit" class="btn btn-primary mt-3">Voltar para Página Inicial</a>
    
    </form>
</div>




<script src="script.js"></script>

<script src="{{ url_for('static', filename='js/cru.js')  }}"></script>

</body>
</html>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css')  }}">
  </head>
<body>

    <div class="container mt-5">
        <h1>Bem-vindo à Página de Cadastro</h1>

        <!-- Div para se cadastrar -->
        <div class="mt-4 p-4 border rounded">
            <h2>Cadastre-se</h2>
            <p>Faça parte da nossa comunidade. Inscreva-se agora e tenha acesso a todos os benefícios.</p>
            <a href="clientes/cadastrar" class="btn btn-primary">Cadastrar</a>
        </div>

          <!-- Div para ver usuários já cadastrados -->
          <div class="mt-4 p-4 border rounded">
              <h2>Ver Usuários Cadastrados</h2>
              <p>Veja quem já está cadastrado na nossa comunidade.</p>
              <a href="/clientes/" class="btn btn-secondary">Ver Usuários</a>
          </div>
    </div>

    <!-- Link para o JavaScript do Bootstrap (e jQuery) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='js/cru.js')  }}"></script>

</body>
</html>

templates/lista_clientes.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Clientes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
</head>
<body>

    

    
      <h1>Clientes</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Idade</th>
                <th scope="col">Sexo</th>
                <th scope="col">Altura</th>
                <th scope="col">Peso</th>
                <th scope="col">Pressão Arterial</th>
                <th scope="col">Alergias</th>
                <th scope="col">Medicamentos em Uso</th>
                <th scope="col">Fuma</th>
                <th scope="col">Bebe</th>
                <th scope="col">Parentes com Doenças</th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in clientes %}
                <tr>
                    <th scope="row">{{ cliente.id }}</th>
                    <td>{{ cliente.nome }}</td>
                    <td>{{ cliente.idade }}</td>
                    <td>{{ cliente.sexo }}</td>
                    <td>{{ cliente.altura }}</td>
                    <td>{{ cliente.peso }}</td>
                    <td>{{ cliente.pressao_arterial }}</td>
                    <td>{{ cliente.alergias }}</td>
                    <td>{{ cliente.medicamentos_em_uso }}</td>
                    <td>{{ 'Sim' if cliente.fuma else 'Não' }}</td>
                    <td>{{ 'Sim' if cliente.bebe else 'Não' }}</td>
                    <td>{{ cliente.parentes_com_doencas }}</td>

                    
                </tr>
                
            {% endfor %}
        </tbody>
    </table>

    <div class="row">
        <div class="col-md-12 text-center">

            <a href="http://localhost:5000/" class="btn btn-primary mt-3">Voltar para Página Inicial</a>
        </div>
    </div>
  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='js/cru.js')  }}"></script>

</body>
</html>

templates/sucesso.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro Realizado com Sucesso</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1>Usuário Cadastrado com Sucesso!</h1>
                <p class="lead">Obrigado por se cadastrar em nosso site.</p>
                <a href="http://localhost:5000/" class="btn btn-primary mt-3">Voltar para Página Inicial</a>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>